#!/bin/bash


echo "Build API Service..."

## Skipped 'service-api' build, because this build currently fails if the repository is a submodule of another submodule.
#./service-api/repo-management/custom-build bluefu/service-api-with-tfs
CURDIR=$PWD
cd ./build/service-api
git checkout service-api-with-tfs
git pull
repo-management/custom-build bluefu/service-api-with-tfs
cd $CURDIR

echo "...done."
echo
