#!/bin/bash
git submodule init
git submodule update

echo "Initialize service-api"
./service-api/repo-management/init-repo.bash

echo "Initialize service-ui"
./service-ui/repo-management/init-repo.bash

echo "Initialize plugin-bts-tfs"
./plugin-bts-tfs/repo-management/init-repo.bash